GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "Title",
    "author": "Author",
    "url": "Url",
    "likes": 123,
    "userId": "61a27293369fdc6154e417e4"
}

###

DELETE http://localhost:3001/api/blogs/619c064797982bf3a6b54abe

###

PUT http://localhost:3001/api/blogs/619c064797982bf3a6b54abe 
content-type: application/json

{
    "title": "Title",
    "author": "Author",
    "url": "Url",
    "likes": 2,
    "id": "619c064797982bf3a6b54abe"
}
