GET http://localhost:3001/api/blogs
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhd2VsenlzayIsImlkIjoiNjFhMjcyOTMzNjlmZGM2MTU0ZTQxN2U0IiwiaWF0IjoxNjM4MTM2MTM3fQ.YcW8365DhMGk1Hb95052OaXILGcSPY7xWyROdFtvsHo

###

POST http://localhost:3001/api/blogs
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhd2VsenlzayIsImlkIjoiNjFhMjcyOTMzNjlmZGM2MTU0ZTQxN2U0IiwiaWF0IjoxNjM4MTM2MTM3fQ.YcW8365DhMGk1Hb95052OaXILGcSPY7xWyROdFtvsHo


{
    "title": "Title",
    "author": "Author",
    "url": "Url",
    "likes": 123,
    "userId": "61a27293369fdc6154e417e4"
}

###

DELETE http://localhost:3001/api/blogs/619c064797982bf3a6b54abe

###

PUT http://localhost:3001/api/blogs/619c064797982bf3a6b54abe 
content-type: application/json

{
    "title": "Title",
    "author": "Author",
    "url": "Url",
    "likes": 2,
    "id": "619c064797982bf3a6b54abe"
}
